### ISSUE TITLE
Some .ndpi files do not open when extension installed

### ISSUE THREAD

**Issue by SachaNYC** [qupath/qupath-bioformats-extension#2]
This QuPath bioformats extension prevents me from opening some .ndpi files by returning the error messages below (error reading image region). I can still open these same files with QuPath if I remove this extension from the folder and just keep the bioformats package, but the process is then quite slow for very large files.

I have not figured out why some .ndpi files open without issue even with the extension installed, while others don't. It is not related to file size, but may be related to slides that needed rescanning. Still, the fact that these slides can be read without the extension but not with it is puzzling, as the extension is supposed to help.

Any suggestion would be welcome, as I am new to the .ndpi format, and never had issues opening files with the .mxrs format.

Thanks.

Sacha

ERROR: Error reading image region
    at loci.formats.in.NDPIReader.openBytes(NDPIReader.java:175)
    at loci.formats.FormatReader.openBytes(FormatReader.java:886)
    at loci.formats.ImageReader.openBytes(ImageReader.java:441)
    at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
    at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
    at qupath.lib.images.servers.BioformatsImageServer.readBufferedImage(BioformatsImageServer.java:525)
    at qupath.lib.images.servers.BioformatsImageServer.readBufferedImage(BioformatsImageServer.java:76)
    at qupath.lib.images.servers.AbstractImageServer.getBufferedThumbnail(AbstractImageServer.java:70)
    at qupath.lib.images.servers.BioformatsImageServer.getBufferedThumbnail(BioformatsImageServer.java:645)
    at qupath.lib.images.servers.BioformatsImageServer.getBufferedThumbnail(BioformatsImageServer.java:76)
    at qupath.lib.gui.helpers.DisplayHelpers.estimateImageType(DisplayHelpers.java:117)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2269)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2258)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2236)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2152)
    at qupath.extensions.OSXExtension.lambda$2(OSXExtension.java:117)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
ERROR: QuPath exception
    at qupath.lib.gui.helpers.DisplayHelpers.estimateImageType(DisplayHelpers.java:125)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2269)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2258)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2236)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2152)
    at qupath.extensions.OSXExtension.lambda$2(OSXExtension.java:117)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

ERROR: Error reading image region
    at loci.formats.in.NDPIReader.openBytes(NDPIReader.java:175)
    at loci.formats.FormatReader.openBytes(FormatReader.java:886)
    at loci.formats.ImageReader.openBytes(ImageReader.java:441)
    at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
    at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
    at qupath.lib.images.servers.BioformatsImageServer.readBufferedImage(BioformatsImageServer.java:525)
    at qupath.lib.images.servers.BioformatsImageServer.readBufferedImage(BioformatsImageServer.java:76)
    at qupath.lib.images.stores.AbstractImageRegionStore$DefaultTileWorker$1.call(AbstractImageRegionStore.java:656)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by petebankhead** [comment]
Thanks for reporting this.  I'm actually looking at the Bio-Formats extension code right now... it has a few problems, although I wasn't aware of this one.  It has worked with any NDPI files I'd tried - but not NDPIS (which is one of the problems).

I hope to have a new version of the extension ready in the next day or two; I'll write again here when it's available.  It would be good to know if the problem persists.

If the Bio-Formats extension isn't available, QuPath will use OpenSlide for NDPI instead.  I guess this is working more reliably for you.  The reason why the Bio-Formats extension 'takes control' when installed is because it also supports NDPI z-stacks or fluorescence, which aren't supported by OpenSlide.  And when the image is being opened, QuPath doesn't necessarily know which it is going to be - so tries to err on the side of caution and prefer the flexibility of Bio-Formats.  But your experience shows that there needs to be a way to control this, without having to resort to removing the extension...

**Comment by SachaNYC** [comment]
Thanks for the very rapid answer. I will keep an eye on the new extension. Thanks!

**Comment by petebankhead** [comment]
The new extension is now [here](https://github.com/qupath/qupath-bioformats-extension/releases/tag/v0.0.4).

You can now choose to disable the use of Bio-Formats for .ndpi if there is still trouble after the update.  Just type `.ndpi` in the *Always use Bio-Formats...* entry under *Edit &rarr; Preferences...*

**Comment by SachaNYC** [comment]
Thanks for the new extension (v.0.0.4). Unfortunately, it still will not open some ndpi files, but as mentioned, they can now be excluded. If I figure out what triggers the "Error reading image region" in only some files, I'll let you know.

**Comment by petebankhead** [comment]
This morning I've learned of a problem in QuPath's TIFF-image-checking that results in some large .ndpi files not working.... even though OpenSlide and Bio-Formats _could_ otherwise handle them.

Until a proper fix is available, this script will circumvent the check and allow you to select the image to open from a file chooser.  I don't know for sure if it will play nicely with projects (it accesses the viewer directly), but is hopefully a start.

```groovy
guiscript=true

/**
 * Workaround to open an image directly using OpenSlide, and skip the TIFF check.
 *
 * This helps resolve issues with large .ndpi files, where QuPath's built-in
 * TIFF check can fail to complete in any reasonable timeframe.
 */

import qupath.lib.gui.QuPathGUI
import qupath.lib.images.ImageData

def file = QuPathGUI.getDialogHelper(null).promptForFile(null)
if (file == null)
    return

def viewer = QuPathGUI.getInstance().getViewer()
def server = new qupath.lib.images.servers.OpenslideImageServer(file.getPath())
def imageData = new ImageData(server)
viewer.setImageData(imageData)
```

**Comment by SachaNYC** [comment]
Thank you Pete, we will try the script.

Sacha


On Nov 12, 2018, at 6:59 AM, Pete <notifications@github.com<mailto:notifications@github.com>> wrote:


This morning I've learned of a problem in QuPath's TIFF-image-checking that results in some large .ndpi files not working.... even though OpenSlide and Bio-Formats could otherwise handle them.

Until a proper fix is available, this script will circumvent the check and allow you to select the image to open from a file chooser. I don't know for sure if it will play nicely with projects (it accesses the viewer directly), but is hopefully a start.

guiscript=true

/**
 * Workaround to open an image directly using OpenSlide, and skip the TIFF check.
 *
 * This helps resolve issues with large .ndpi files, where QuPath's built-in
 * TIFF check can fail to complete in any reasonable timeframe.
 */

import qupath.lib.gui.QuPathGUI
import qupath.lib.images.ImageData

def file = QuPathGUI.getDialogHelper(null).promptForFile(null)
if (file == null)
    return

def viewer = QuPathGUI.getInstance().getViewer()
def server = new qupath.lib.images.servers.OpenslideImageServer(file.getPath())
def imageData = new ImageData(server)
viewer.setImageData(imageData)
