### ISSUE TITLE
Error Opening .CZI Files with Latest Extension

### ISSUE THREAD

**Issue by LewisSwansea** [qupath/qupath-bioformats-extension#8]
This QuPath bioformats extension prevents me from opening some .czi files by returning the error messages below.

Any suggestion as to why this is the case would be extremely helpful as I am new to using QuPath and the current extensions to allow me to open these types of files.

Thanks.

Lewis

INFO: Refreshing extensions in C:\Users\QuPath\extensions
INFO: Added extension: C:\Users\QuPath\extensions\bioformats_package (5).jar
INFO: Added extension: C:\Users\QuPath\extensions\qupath-extension-bioformats (4).jar
INFO: Bio-Formats version 5.9.0
INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: Project set to Project: Project Test
WARN: Unable to open F:\Slide Scanning\2018_08_02__3365.czi with OpenSlide: F:\Slide Scanning\2018_08_02__3365.czi: Not a file that OpenSlide can recognize
WARN: Error opening F:\Slide Scanning\2018_08_02__3365.czi with ImageJ: Could not open F:\Slide Scanning\2018_08_02__3365.czi with ImageJ
WARN: Unable to open F:\Slide Scanning\2018_08_02__3365.czi with OpenSlide: F:\Slide Scanning\2018_08_02__3365.czi: Not a file that OpenSlide can recognize
WARN: Error opening F:\Slide Scanning\2018_08_02__3365.czi with ImageJ: Could not open F:\Slide Scanning\2018_08_02__3365.czi with ImageJ
INFO: Returning server: Bio-Formats for F:\Slide Scanning\2018_08_02__3365.czi
ERROR: java.lang.UnsatisfiedLinkError: ome.jxrlib.JXRJNI.new_DecodeContext()J
ERROR: QuPath exception
    at ome.jxrlib.JXRJNI.new_DecodeContext(Native Method)
    at ome.jxrlib.DecodeContext.<init>(DecodeContext.java:43)
    at ome.jxrlib.AbstractDecode.decodeFirstFrame(AbstractDecode.java:101)
    at ome.jxrlib.Decode.decodeFirstFrame(Decode.java:51)
    at loci.formats.services.JPEGXRServiceImpl.decompress(JPEGXRServiceImpl.java:53)
    at loci.formats.codec.JPEGXRCodec.decompress(JPEGXRCodec.java:84)
    at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3712)
    at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3669)
    at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3664)
    at loci.formats.in.ZeissCZIReader.openBytes(ZeissCZIReader.java:394)
    at loci.formats.FormatReader.openBytes(FormatReader.java:886)
    at loci.formats.ImageReader.openBytes(ImageReader.java:444)
    at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
    at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
    at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
    at qupath.lib.images.servers.BioFormatsImageServer.readBufferedImage(BioFormatsImageServer.java:683)
    at qupath.lib.images.servers.BioFormatsImageServer.readBufferedImage(BioFormatsImageServer.java:95)
    at qupath.lib.images.stores.AbstractImageRegionStore.getThumbnail(AbstractImageRegionStore.java:354)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2269)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2258)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2236)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2152)
    at qupath.lib.gui.QuPathGUI.openImageEntry(QuPathGUI.java:2115)
    at qupath.lib.gui.panels.ProjectBrowser.lambda$new$1(ProjectBrowser.java:145)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
INFO: Returning server: Bio-Formats for F:\Slide Scanning\2018_08_02__3365.czi

**Comment by petebankhead** [comment]
It looks like it's related to JPEG-XR compression - you may need to install the  _Visual Studio 2015 C++ Redistributable_, see https://github.com/qupath/qupath/wiki/Supported-image-formats#zeiss-czi

**Comment by LewisSwansea** [comment]
Thanks Pete!

That sorted out the problem!!
